name: Build and Test
on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  build_and_test:
    name: Build and run tests
    runs-on: ubuntu-latest
    services:
        postgres:
            image: postgres:10
            env:
                POSTGRES_USER: postgres
                POSTGRES_PASSWORD: postgres
                POSTGRES_DB: sequelize
            ports:
                - 5432/tcp
            options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      matrix:
        node-version: [10, 12, 14, 16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: |
            find ./test/fixtures -path "*/config/*" -not -path "*/node_modules/*" \( -name "datastores.js" -or -name "connections.js" \) -exec sed -i -e "s/: 'localhost'/: 'postgres'/g" {} \;
      - run: npm ci
      - run: npm test
        env:
            PGPASSWORD: postgres
      - name: Create test coverage report
        run: ./node_modules/nyc/bin/nyc.js report --reporter=lcovonly
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
